using System.Text;
using YamlDotNet.RepresentationModel;

if (args.Length < 2)
{
    Console.Error.WriteLine("Usage: EntityIdGenerator <configYaml> <outputCs>");
    return 1;
}

var inputPath = args[0];
var outputPath = args[1];

if (!File.Exists(inputPath))
{
    Console.Error.WriteLine($"Config file not found: {inputPath}");
    return 2;
}

var yaml = File.ReadAllText(inputPath);
var yamlStream = new YamlStream();
using (var reader = new StringReader(yaml))
{
    yamlStream.Load(reader);
}

if (yamlStream.Documents.Count == 0)
{
    Console.Error.WriteLine("Config YAML is empty.");
    return 3;
}

var root = yamlStream.Documents[0].RootNode as YamlMappingNode;
if (root == null || !root.Children.TryGetValue(new YamlScalarNode("hardware"), out var hardwareNode))
{
    Console.Error.WriteLine("Config missing 'hardware' section.");
    return 4;
}

if (hardwareNode is not YamlMappingNode hardwareMap)
{
    Console.Error.WriteLine("'hardware' section must be a mapping.");
    return 5;
}

var names = new List<string>();

foreach (var entry in hardwareMap.Children)
{
    var hardwareName = (entry.Key as YamlScalarNode)?.Value ?? string.Empty;
    if (entry.Value is not YamlMappingNode entryMap)
    {
        continue;
    }

    if (!entryMap.Children.TryGetValue(new YamlScalarNode("config"), out var configNode))
    {
        continue;
    }

    CollectEntriesRecursive(configNode, hardwareName, names);
}

var mappings = names
    .Select(name => (SystemName: name, EnumName: ToEnumName(name)))
    .Where(item => !string.IsNullOrWhiteSpace(item.EnumName))
    .ToList();

var unique = mappings
    .Select(item => item.EnumName)
    .Distinct(StringComparer.OrdinalIgnoreCase)
    .OrderBy(name => name, StringComparer.OrdinalIgnoreCase)
    .ToList();

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated />");
sb.AppendLine("namespace PickAndPlace.Entities;");
sb.AppendLine();
sb.AppendLine("public enum EntityId");
sb.AppendLine("{");
foreach (var name in unique)
{
    sb.AppendLine($"    {name},");
}
sb.AppendLine("}");
sb.AppendLine();
sb.AppendLine("public static class EntityIdMap");
sb.AppendLine("{");
sb.AppendLine("    public static readonly IReadOnlyDictionary<EntityId, string> SystemNames =");
sb.AppendLine("        new Dictionary<EntityId, string>");
sb.AppendLine("        {");
foreach (var name in unique)
{
    var systemName = mappings.First(item => string.Equals(item.EnumName, name, StringComparison.OrdinalIgnoreCase)).SystemName;
    sb.AppendLine($"            [EntityId.{name}] = \"{systemName}\",");
}
sb.AppendLine("        };");
sb.AppendLine("}");
sb.AppendLine();
sb.AppendLine("public static class EntityIdExtensions");
sb.AppendLine("{");
sb.AppendLine("    public static string ToSystemName(this EntityId id) => EntityIdMap.SystemNames[id];");
sb.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
File.WriteAllText(outputPath, sb.ToString());

return 0;

static string ToEnumName(string raw)
{
    var tokens = new List<string>();
    var current = new StringBuilder();

    foreach (var ch in raw)
    {
        if (char.IsLetterOrDigit(ch))
        {
            current.Append(ch);
            continue;
        }

        if (current.Length > 0)
        {
            tokens.Add(current.ToString());
            current.Clear();
        }
    }

    if (current.Length > 0)
    {
        tokens.Add(current.ToString());
    }

    if (tokens.Count == 0)
    {
        return string.Empty;
    }

    var sb = new StringBuilder();
    foreach (var token in tokens)
    {
        if (string.IsNullOrWhiteSpace(token))
        {
            continue;
        }

        if (char.IsDigit(token[0]))
        {
            sb.Append('_');
        }

        sb.Append(char.ToUpperInvariant(token[0]));
        if (token.Length > 1)
        {
            sb.Append(token[1..]);
        }
    }

    return sb.ToString();
}

static string NormalizeSegment(string raw)
{
    if (string.IsNullOrWhiteSpace(raw))
    {
        return string.Empty;
    }

    var sb = new StringBuilder();
    foreach (var ch in raw.Trim())
    {
        if (char.IsLetterOrDigit(ch) || ch == '_')
        {
            sb.Append(char.ToLowerInvariant(ch));
        }
        else if (char.IsWhiteSpace(ch) || ch == '.' || ch == '-')
        {
            sb.Append('_');
        }
    }

    return sb.ToString();
}

static void CollectIoPoints(YamlNode ioPointsNode, string hardwareName, string prefix, List<string> names)
{
    if (ioPointsNode is not YamlSequenceNode ioPoints)
    {
        return;
    }

    foreach (var item in ioPoints)
    {
        if (item is not YamlMappingNode point)
        {
            continue;
        }

        string? id = null;
        if (point.Children.TryGetValue(new YamlScalarNode("id"), out var idNode))
        {
            id = (idNode as YamlScalarNode)?.Value;
        }

        if (!string.IsNullOrWhiteSpace(id))
        {
            var prefixSegment = NormalizeSegment(hardwareName);
            var segment = NormalizeSegment(id);
            var full = string.IsNullOrWhiteSpace(prefixSegment)
                ? segment
                : $"{prefixSegment}.{prefix}.{segment}";
            names.Add(full);
        }
    }
}

static void CollectEntriesRecursive(YamlNode node, string hardwareName, List<string> names)
{
    if (node is YamlMappingNode map)
    {
        foreach (var entry in map.Children)
        {
            if (entry.Key is YamlScalarNode key &&
                string.Equals(key.Value, "common_io", StringComparison.OrdinalIgnoreCase))
            {
                CollectIoPoints(entry.Value, hardwareName, "io", names);
            }
            else if (entry.Key is YamlScalarNode key2 &&
                string.Equals(key2.Value, "io", StringComparison.OrdinalIgnoreCase))
            {
                CollectIoPoints(entry.Value, hardwareName, "io", names);
            }
            else if (entry.Key is YamlScalarNode key3 &&
                string.Equals(key3.Value, "data", StringComparison.OrdinalIgnoreCase))
            {
                CollectIoPoints(entry.Value, hardwareName, "data", names);
            }
            else
            {
                CollectEntriesRecursive(entry.Value, hardwareName, names);
            }
        }
    }
    else if (node is YamlSequenceNode seq)
    {
        foreach (var item in seq)
        {
            CollectEntriesRecursive(item, hardwareName, names);
        }
    }
}
