<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Core\NAutoSuite.Core\NAutoSuite.Core.csproj" />
    <ProjectReference Include="..\..\Hardware\NAutoSuite.Hardware.Simulator\NAutoSuite.Hardware.Simulator.csproj" />
    <ProjectReference Include="..\..\UI\NAutoSuite.UI.Infrastructure\NAutoSuite.UI.Infrastructure.csproj" />
    <ProjectReference Include="..\..\UI\NAutoSuite.UI.Themes\NAutoSuite.UI.Themes.csproj" />
    <ProjectReference Include="..\..\UI\NAutoSuite.UI.Controls\NAutoSuite.UI.Controls.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
