<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NAutoSuite.Hardware.Abstractions\NAutoSuite.Hardware.Abstractions.csproj" />
    <ProjectReference Include="..\..\Core\NAutoSuite.Core\NAutoSuite.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>

</Project>
